#!/bin/bash

export TMP_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970

/home/steam/burpenheim/valheim_server.x86_64 \
    -nographics \
    -batchmode \
    -name "Boy Meets Burp" \
    -port 2456 \
    -world "Burpenhiem" \
    -password "burpcraft" \
    -public 0 \
    -savedir "/home/steam/burpenheim/GameData"

export LD_LIBRARY_PATH=$TMP_LD_LIBRARY_PATH