#!/bin/bash

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/steam/burpenheim/valheim_server_Data/Plugins/x86_64 /home/burpenheim/valheim/valheim_server \
    -nographics \
    -batchmode \
    -name "Boy Meets Burp" \
    -port 2456 \
    -world "Burpenhiem" \
    -password "burpcraft" \
    -public 0 \
    -savedir "/home/steam/valheim/GameData"
